apiVersion: apps/v1
kind: Deployment
metadata:
  name: hgkrwi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hgkrwi
  template:
    metadata:
      labels:
        app: hgkrwi
    spec:
      containers:
      - image: okteto.dev/myu:latest
        name: hgkrwi
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "94259580-03a8-4546-9da4-653eec77db7f"
        - name: Vless_Path
          value: "/94259580-03a8-4546-9da4-653eec77db7f-vless"
        - name: Vmess_UUID
          value: "94259580-03a8-4546-9da4-653eec77db7f"
        - name: Vmess_Path
          value: "/17943e0b-e0c2-49c9-8334-074f8950b503-vmess"
        - name: Share_Path
          value: "/v2link"
